---
title: Week 7 Blog
author: Haroon, Leo, Ryan, Benni
date: '2022-12-02'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-12-02T09:36:24-05:00'
featuredVideo: ~
featuredImage: ~
---

## Thesis:

Oftentimes in sports, we say players are on “hot streaks” if they perform above a certain standard for multiple consecutive games. Our goals with this project include defining the standard against which a streak can be determined, identifying streaks based on this standard, and drawing comparisons between streaks in two sports leagues in particular: the NBA and the MLB. We aim to see if the streakiness of players and teams are localized to their respective sports, or certain transcendental properties emerge between the two sports. To accomplish this goal, we have split the project into two separate tasks. We will first perform our analyses with respect to each league to gain insight into how streaks are distributed in their respective leagues, and then we will combine our findings to determine whether any relationships exist between baseball and basketball players. We have defined streaks as a player performing above their average in a specific stat, or a combination of stats in a number of successive games. We also suggest that not only is there a method to predict when these players get on “hot streaks,” but we can perform similar analyses across different sports, and even identify whether certain players are “streaky” in general. We believe our findings will be of interest to people who want to better understand and predict streaks in these two leagues, like those participating in fantasy sports and sports betting, and it will build on currently available metrics to predict a player or team’s performance.



