---
title: "Leo_MLB_EDA"
author: "Leo Seoane"
date: "2022-12-07"
output: html_document
---

---
title: "Leo_EDA_2"
author: "Leo Seoane"
date: "2022-11-09"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(here))
suppressPackageStartupMessages(library(modelr))
```
```{r data loading}
load(here::here("dataset", "MLB_bat_data.RData"))
problems()

```

```{r Final player EDA}
#get all of our data by players who meet criteria and calculate streaks
all_data <-data %>% group_by(player)  %>% filter(mean(minutes) >25,minutes >15) %>% mutate(change_net = pts - mean(pts),pts_direction  = 
sign(change_net),change_net_PRA=PRA - mean(PRA),PRA_direction=sign(change_net_PRA)) %>%mutate(pts_streak=ave(pts_direction, cumsum(pts_direction==-1), FUN = seq_along) - 1,PRA_streak=ave(PRA_direction, cumsum(PRA_direction==-1), FUN = seq_along) - 1)
all_data <-all_data  %>% mutate(Team_def_rtg=mean(Opponent_Score/Opponent_pace *100), Opponent_def_rtg=mean(Team_Score/Team_pace *100))

#visualize distribution of positive player points streaks and PRA streaks
streak <-all_data$pts_streak
indices<-which(diff(sign(diff(streak)))==-2)+1
local_max <-slice(all_data,indices)
local_max<-local_max %>%group_by(player) %>% select(pts_streak,change_net,change_net_PRA,PRA_streak) %>%filter(pts_streak >0,PRA_streak >0)
summary(local_max)
ggplot(local_max) +geom_freqpoly(aes(x=pts_streak))
ggplot(local_max) +geom_freqpoly(aes(x=PRA_streak))


#view proportion of  maximum continuing streaks for best, middle, and worst players
all_streaks_2022 <- local_max %>% summarize(max_streak=max(mean(pts_streak))) %>% arrange(desc(max_streak))
best_streaks_2022 <- all_streaks_2022 %>%head(5)
bottom_streaks_2022 <- all_streaks_2022 %>% tail(5)
ggplot(best_streaks_2022) +geom_col(aes(y=max_streak,x=player))
ggplot(bottom_streaks_2022) +geom_col(aes(y=max_streak,x=player))

#PRA
all_PRA_streaks_2022 <- local_max %>% summarize(max_streak=max(mean(PRA_streak))) %>% arrange(desc(max_streak))
best_PRA_streaks_2022 <- all_PRA_streaks_2022 %>%head(5)
bottom_PRA_streaks_2022 <- all_PRA_streaks_2022 %>% tail(5)
ggplot(best_PRA_streaks_2022) +geom_col(aes(y=max_streak,x=player))
ggplot(bottom_PRA_streaks_2022) +geom_col(aes(y=max_streak,x=player))



#cdf and pdf for player points
ggplot(best_streaks_2022,aes(max_streak))+stat_ecdf(geom = "step")
ggplot(best_streaks_2022,aes(max_streak))+geom_density()
ggplot(top_player_data22,aes(pts)) +geom_density()

#model building by player
mod1 <-all_data %>%ungroup() %>% glm(formula=factor(pts_direction)~ts_pct+usg_pct+usg_pct:ts_pct,family=binomial())
mod1$coefficients
exp(mod1$coefficients)

all_data <-all_data %>%mutate(pts_direction=ifelse(pts_direction==-1,0,1))

grid <- data_grid(ungroup(all_data), ts_pct= seq_range(ts_pct,100),usg_pct= seq_range(usg_pct,5)) %>% add_predictions(mod1, type = "response" )

ggplot(all_data) +geom_line(aes(x=ts_pct,y=pred,color = factor(usg_pct)),data=grid)

scoring<-all_data %>% filter(player == 'Brandon Ingram',season == '2022') %>%select(change_net,game_date)
ggplot(scoring, aes(x=as.Date(as.factor(game_date)), y=change_net, group=1)) +
geom_ribbon(aes(ymin=pmin(change_net,0), ymax=0), fill="red", col="red", alpha=0.5) +
geom_ribbon(aes(ymin=0, ymax=pmax(change_net,0)), fill="green", col="green", alpha=0.5) +
geom_point()+
geom_line(aes(y=0)) + ggtitle('Change') +
ylab('Points Deviated from Average') +
xlab('Date')





```