---
title: "Ryan_EDA"
output: html_document
date: "2022-10-20"
---

```{r Data Cleaning}
library(tidyverse)
library(ggrepel)

bat_data_21 <- read_csv("dataset/MLB_bat_data_2021.csv") %>%
  select(-game_id, -player_id, -details, -batting_order, -DKP, -FDP, -SDP) %>%
  mutate(singles = h - (doubles + triples + home_runs),
         tb = singles + 2*doubles + 3*triples + 4*home_runs,
         on_base = h + bb + hit_by_pitch)

bat_data_21 %>% arrange(game_date) %>% group_by(player) %>%
  filter(sum(home_runs) >= 40) %>% mutate(hr = cumsum(home_runs)) %>%
  ggplot(aes(x = game_date, y = hr, color = player, group = player)) +
  geom_line()

ops_data_21 <- bat_data_21 %>% group_by(player) %>%
  summarize(ab = sum(ab),
            pa = sum(pa),
            tb = sum(tb),
            on_base = sum(on_base)) %>% 
  mutate(obp = on_base/pa, slg = tb/ab, ops = obp + slg) %>% 
  arrange(desc(ops))

ops_data_21 %>% filter(pa >= 500, ops >= .9) %>%
  ggplot(aes(x = pa, y = ops)) + geom_point() +
  geom_text_repel(aes(label = player), size = 3) +
  labs(title = ".900+ OPS Hitters vs Plate Appearances",
       x = "Plate Appearances", y = "OPS")

ops_data_month <- bat_data_21 %>% separate(game_date,
                                      into = c("year", "month", "day")) %>% 
  group_by(player, month) %>%
  summarize(ab = sum(ab),
            pa = sum(pa),
            tb = sum(tb),
            on_base = sum(on_base)) %>% 
  mutate(obp = on_base/pa, slg = tb/ab, ops = obp + slg) %>% 
  arrange(desc(ops))

ops_data_month %>%
  filter(player %in% filter(ops_data, pa >= 500, ops >= 0.9)$player,
         month != 10) %>% 
  ggplot(aes(month, ops, color = player, group = player)) + geom_point() +
  geom_line()
```

```{r MLB}
library(tidyverse)
library(modelr)
library(ggrepel)

stat_fct <- function(x,y){
  ifelse(y > 0, x/y, 0)
}

bat_data_21 <- read_csv("dataset/MLB_bat_data_2021.csv") %>%
  filter(pa > 0) %>%
  select(-game_id, -player_id, -details, -batting_order, -DKP, -FDP, -SDP) %>%
  mutate(singles = h - (doubles + triples + home_runs),
         tb = singles + 2*doubles + 3*triples + 4*home_runs,
         on_base = h + bb + hit_by_pitch) %>%
  arrange(player, game_date)

ops_data_21 <- bat_data_21 %>% group_by(player) %>%
  summarize(ab = sum(ab),
            pa = sum(pa),
            tb = sum(tb),
            on_base = sum(on_base)) %>% 
  mutate(obp = stat_fct(on_base, pa), slg = stat_fct(tb, ab),
         ops = obp + slg) %>% select(player, obp, slg, ops)

MLB_avg_21 <- bat_data_21 %>%
  summarize(ab = sum(ab),
            pa = sum(pa),
            tb = sum(tb),
            on_base = sum(on_base)) %>% 
  mutate(obp = stat_fct(on_base, pa), slg = stat_fct(tb, ab),
         ops = obp + slg) %>% select(obp, slg, ops)

bat_data_day_21 <- left_join(bat_data_21, ops_data_21, by = "player") %>%
  mutate(MLB_diff = MLB_avg_21$ops - ops)

sim_21 <- bat_data_day_21 %>% group_by(player) %>% filter(sum(pa) >= 500) %>%
  group_by(game_date) %>%
  mutate(obp_game = stat_fct(on_base, pa),
         slg_game = stat_fct(tb, ab),
         ops_game = obp_game + slg_game,
         ops_diff = ops_game - MLB_avg_21$ops,
         above = (ops_diff > 0)) %>% ungroup() %>% group_by(player) %>%
  summarize(games_above = sum(above), games = n(), per = games_above/games,
            ops = mean(ops), pa = sum(pa), home_runs = sum(home_runs),
            bb = sum(bb), so = sum(so))
  
model_21 <- lm(per ~ ops, data = sim_21)
beta <- coef(model_21)
summary(model_21)
ggplot(sim_21, aes(ops, per)) + geom_point() +
  geom_abline(intercept = beta[1], slope = beta[2], color = "red") +
  labs(x = "OPS", y = "% of Games Above League Average")

s_res_21 <- rstandard(model_21)
sim_21 %>% cbind(s_res_21) %>%  ggplot(aes(ops, s_res_21)) +
  geom_ref_line(h = 0) + geom_point()

sim_21 %>% cbind(s_res_21) %>%  filter(abs(s_res_21) >= 2)

sim_21 %>% cbind(s_res_21) %>%
  mutate(streaky = ifelse(s_res_21 < 0, 1, 0)) %>%
  ggplot(aes(ops, streaky)) + geom_point()



bat_data_day_21 %>% filter(player == "Nathaniel Lowe") %>%
  group_by(game_date) %>%
  mutate(obp_game = stat_fct(on_base, pa),
         slg_game = stat_fct(tb, ab),
         ops_game = obp_game + slg_game,
         ops_diff = ops_game - ops,
         sign = sign(ops_diff)) %>%
  ggplot() +
  geom_col(aes(game_date, ops_diff, fill = sign), position = "identity",
           show.legend = FALSE) +
  geom_line(aes(game_date, mean(MLB_diff)), color = "red") +
  labs(title = "Nathaniel Lowe Game by Game OPS Data",
       x = "Date", y = "Game OPS compared to average")



log_sim_21 <- sim_21 %>% cbind(s_res_21) %>%
  mutate(streaky = ifelse(s_res_21 < 0, 1, 0))

lm_hr <- lm(s_res_21 ~ home_runs, data = log_sim_21)
(bt_hr <- coef(lm_hr))
ggplot(log_sim_21, aes(home_runs, s_res_21)) + geom_point() +
    geom_abline(intercept = bt_hr[1], slope = bt_hr[2], color = "red")

lm_bb <- lm(s_res_21 ~ bb, data = log_sim_21)
(bt_bb <- coef(lm_bb))
ggplot(log_sim_21, aes(bb, s_res_21)) + geom_point() +
    geom_abline(intercept = bt_bb[1], slope = bt_bb[2], color = "red")

lm_so <- lm(s_res_21 ~ so, data = log_sim_21)
bt_so <- coef(lm_so)
summary(lm_so)
ggplot(log_sim_21, aes(so, s_res_21)) + geom_point() +
  geom_abline(intercept = bt_so[1], slope = bt_so[2], color = "red") +
  labs(x = "Strikeouts", y = "Streakiness (Residual)")

log_model_hr <- glm(streaky ~ home_runs, data = log_sim_21, family = binomial)
(beta_hr <- coef(log_model_hr))
(grid_hr <- log_sim_21 %>% data_grid(home_runs) %>%
    add_predictions(log_model_hr, type = "response"))
ggplot(log_sim_21, aes(home_runs)) + geom_point(aes(y = streaky)) +
  geom_line(aes(y = pred), data = grid_hr, color = "red", size = 1)

log_model_bb <- glm(streaky ~ bb, data = log_sim_21, family = binomial)
(beta_bb <- coef(log_model_bb))
(grid_bb <- log_sim_21 %>% data_grid(bb) %>%
    add_predictions(log_model_bb, type = "response"))
ggplot(log_sim_21, aes(bb)) + geom_point(aes(y = streaky)) +
  geom_line(aes(y = pred), data = grid_bb, color = "red", size = 1)

log_model_so <- glm(streaky ~ so, data = log_sim_21, family = binomial)
beta_so <- coef(log_model_so)
grid_so <- log_sim_21 %>% data_grid(so) %>%
    add_predictions(log_model_so, type = "response")
summary(log_model_so)
ggplot(log_sim_21, aes(so)) + geom_point(aes(y = streaky)) +
  geom_line(aes(y = pred), data = grid_so, color = "red", size = 1) +
  labs(x = "Strikeouts", y = "Streakiness (Binomial)")
```

```{r NBA}
library(tidyverse)
library(modelr)
library(ggrepel)

load(here::here("dataset", "clean_nba_data.RData"))

NBA_data <- data %>% filter(did_not_play == 0, is_inactive == 0,
                            season == 2022) %>% select(-c(3:21))

ppg_data <- NBA_data %>% group_by(player) %>%
  summarize(ppg = sum(pts)/n(), epm = sum(plus_minus)/n(),
            minutes_tot = sum(minutes)) %>% 
  arrange(desc(ppg))

NBA_avg <- ppg_data %>% group_by(player) %>% filter(minutes_tot >= 2000) %>%
  ungroup() %>% summarize(avg_ppg = mean(ppg), med_ppg = median(ppg),
                          avg_epm = mean(epm))

NBA_data_day <- left_join(NBA_data, ppg_data, by = "player") %>%
  mutate(NBA_diff = NBA_avg$avg_epm - epm)

sim <- NBA_data_day %>% group_by(player) %>% filter(minutes_tot >= 2000) %>%
  group_by(game_date) %>%
  mutate(epm_diff = plus_minus - NBA_avg$avg_epm, above = (epm_diff > 0)) %>%
  ungroup() %>% group_by(player) %>%
  summarize(games_above = sum(above), games = n(), per = games_above/games,
            epm = mean(epm), up = mean(usg_pct), fga = mean(fga), fta = mean(fta))

model <- lm(per ~ epm, data = sim)
beta_NBA <- coef(model)

s_res <- rstandard(model)

log_sim <- sim %>% cbind(s_res) %>%
  mutate(streaky = ifelse(s_res < 0, 1, 0))

summary(model)
ggplot(sim, aes(epm, per)) + geom_point() +
  geom_abline(intercept = beta_NBA[1], slope = beta_NBA[2], color = "red") +
  labs(x = "Average Plus Minus", y = "% of Games with 2+ Plus Minus")



sim %>% cbind(s_res) %>%  ggplot(aes(epm, s_res)) +
  geom_ref_line(h = 0) + geom_point()

sim %>% cbind(s_res) %>%  filter(abs(s_res) >= 1.5)

NBA_data_day %>% filter(player == "Jayson Tatum") %>%
  group_by(game_date) %>%
  mutate(epm_diff = plus_minus - epm,
         sign = sign(epm_diff)) %>%
  ggplot() +
  geom_col(aes(game_date, epm_diff, fill = sign), position = "identity",
           show.legend = FALSE) +
  geom_line(aes(game_date, mean(NBA_diff)), color = "red") +
  labs(title = "Jayson Tatum Game by Game Plus Minus Data",
       x = "Date", y = "Game Plus Minus compared to average")



lm <- lm(s_res ~ up, data = log_sim)
bt <- coef(lm)
summary(lm)
ggplot(log_sim, aes(up, s_res)) + geom_point() +
  geom_abline(intercept = bt[1], slope = bt[2], color = "red") +
  labs(x = "Usage Rate", y = "Streakiness (Residual)")

log_model <- glm(streaky ~ up, data = log_sim, family = binomial)
beta <- coef(log_model)
grid <- log_sim %>% data_grid(up) %>%
    add_predictions(log_model, type = "response")
summary(log_model)
ggplot(log_sim, aes(up)) + geom_point(aes(y = streaky)) +
  geom_line(aes(y = pred), data = grid, color = "red", size = 1) +
  labs(x = "Usage Rate", y = "Streakiness (Binomial)")
```

