---
title: Analysis
description:
toc: true
featuredVideo:
featuredImage: https://i0.wp.com/reflectionsonbaseball.com/wp-content/uploads/2020/01/mlbnba.png?fit=604%2C323&ssl=1
draft: false
---


<div id="TOC">

</div>

<div id="motivations-of-our-data-analysis" class="section level2">
<h2>Motivations of Our Data Analysis:</h2>
<p>What motivates our analysis is a desire to examine the relationship between trends in both the MLB and NBA, and see what comparisons we can draw between the two leagues, especially in regards to player streakiness. We define a streak as the measure of the number of consecutive games a player performs above their average in a specific statistic. We define streakiness as a players propensity to perform above their average, and to what degree over the course of a season. We specifically focus on positive streaks because our goal is to understand player success as opposed to player failure. Additionally, we define pace streakiness as the variation in a player’s statistical pace throughout the season. The main variables that we are interested in analyzing are hits, walks, home runs and strikeouts in the MLB, and points, rebounds, and assists in the NBA. To accomplish this goal, we have split the project into two separate tasks. We first performed analysis on both the NBA and MLB data separately to gain insight into how streaks are distributed in their respective leagues on a game-to-game basis. Once this was completed, we combined our findings to determine whether any relationships exist between baseball and basketball players. Finally, we take a step back and look at streakiness on the seasonal level by looking at pace variation to compare the effects of streakiness on overall performance in both leagues.</p>
</div>
<div id="nba-eda" class="section level2">
<h2>NBA EDA:</h2>
</div>
<div id="identifying-streaks" class="section level2">
<h2>Identifying Streaks:</h2>
<p>For the NBA data, we first identified the longest streaks in the NBA. This would help us get a sense of which players had the longest streaks for a particular statistic in the league in a given season. The first statistic to look at was points. To assess the longest scoring streaks in the league, we calculated the points per season for each player. The dataset contains game-by-game data for each player, but does not account for entire season statistics. This meant that some cleaning and calculations were necessary. First, as stated in the Data page, any erroneous extra rows were removed. Then the season average in points scored was caclulated by dividing the total points scored by the total number of games played for each player. The field goal percentage was also calculated by dividing the total number of field goal made by the total number offield goal attempts. As seen in the table below, the table now listed the season points and field goal average, grouped by each player. Similarly, the assists and rebounds per game were also calculated. Additionally, we used some advanced metrics to aid us in our inference and analysis. In particular, we use true shooting percentage, offensive rating, and usage rate. TS% is a weighted field goal percentage that accounts for the difference in two and three point shots, and adjusts for free throws. Offensive rating is a metric that uses a per 100 posessions basis for offensive capability including TS%, but it also accounts for turnovers. Usage percentage is a metric of how often the player is used in a team’s offense, which is relevant for determining how much player’s will score.</p>
<table style="width:100%;">
<colgroup>
<col width="24%" />
<col width="16%" />
<col width="14%" />
<col width="18%" />
<col width="13%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">player</th>
<th align="right">total_games</th>
<th align="right">ppg</th>
<th align="right">fg_percentage</th>
<th align="right">apg</th>
<th align="right">rpg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Aaron Gordon</td>
<td align="right">75</td>
<td align="right">15.0133333</td>
<td align="right">0.5203837</td>
<td align="right">2.5066667</td>
<td align="right">5.8400000</td>
</tr>
<tr class="even">
<td align="left">Aaron Henry</td>
<td align="right">6</td>
<td align="right">0.3333333</td>
<td align="right">0.2000000</td>
<td align="right">0.0000000</td>
<td align="right">0.1666667</td>
</tr>
<tr class="odd">
<td align="left">Aaron Holiday</td>
<td align="right">63</td>
<td align="right">6.3492063</td>
<td align="right">0.4467456</td>
<td align="right">2.4285714</td>
<td align="right">1.9365079</td>
</tr>
<tr class="even">
<td align="left">Aaron Nesmith</td>
<td align="right">52</td>
<td align="right">3.7692308</td>
<td align="right">0.3956044</td>
<td align="right">0.4230769</td>
<td align="right">1.7115385</td>
</tr>
<tr class="odd">
<td align="left">Aaron Wiggins</td>
<td align="right">50</td>
<td align="right">8.3200000</td>
<td align="right">0.4629080</td>
<td align="right">1.3600000</td>
<td align="right">3.5600000</td>
</tr>
<tr class="even">
<td align="left">Abdel Nader</td>
<td align="right">14</td>
<td align="right">2.4285714</td>
<td align="right">0.3428571</td>
<td align="right">0.5000000</td>
<td align="right">1.9285714</td>
</tr>
<tr class="odd">
<td align="left">Ade Murkey</td>
<td align="right">1</td>
<td align="right">0.0000000</td>
<td align="right">NaN</td>
<td align="right">0.0000000</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">Admiral Schofield</td>
<td align="right">38</td>
<td align="right">3.8421053</td>
<td align="right">0.4186047</td>
<td align="right">0.6578947</td>
<td align="right">2.3421053</td>
</tr>
<tr class="odd">
<td align="left">Ahmad Caver</td>
<td align="right">1</td>
<td align="right">2.0000000</td>
<td align="right">1.0000000</td>
<td align="right">0.0000000</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">Al Horford</td>
<td align="right">69</td>
<td align="right">10.1594203</td>
<td align="right">0.4674868</td>
<td align="right">3.3623188</td>
<td align="right">7.6811594</td>
</tr>
</tbody>
</table>
<p>We will take a look below at the most efficient top scorers. Temporarily setting a threshold for players who scored at least 20 points per game, we made a scatterplot that visualized this relationship to get a sense of who we might expect to have the longest streaks, seen below.</p>
<p>We see above that Lebron James and Joel Embiid scored the most points in the 2022 season, and that they were among the most efficient players in this pool alongside Giannis Antetokounmpo, Nikola Jokic, and Kevin Durant. Because of their prolific and efficient scoring, we at first expected them to be the among the players with the longest streaks. However, after further investigation, we determined that these players were fairly consistent and instead hypothesized that the streakiest players (and therefore the players with the longest streaks) would be those with a lower usage rates and lower scoring - possibly role players who were infrequently given a chances to score above their usual means.</p>
<p>Because we score streaks based on the individual game performance AGAINST their season average, we needed to join the calculated season averages to the entire game-by-game data, as shown below. Additionally, in this merged dataset, we calculated the deviation per game for each of the three following statistics: points, assists, and rebounds. The deviation was calculated as the statistic from one game substracted by that player’s season average in that statistic. For example, 5 <code>pts</code> scored in one game substracted from 10 <code>ppg</code> will result in a <code>deviationppg</code> of -5.</p>
<pre class="r"><code>merged2022 &lt;- nba_ppg22 %&gt;% inner_join(nba_data22, by=&quot;player&quot;) %&gt;%
  filter(mp != &#39;0:00&#39;) %&gt;%
  group_by(player) %&gt;%
  distinct(game_date, .keep_all = TRUE) %&gt;%
  ungroup() %&gt;%
  mutate(date = as.Date(game_date, format = &quot;%Y-%m-%d&quot;)) %&gt;%
  mutate(deviationppg = pts-ppg,
         deviationapg = ast-apg,
         deviationrpg = trb-rpg) %&gt;%
  arrange(player, date)</code></pre>
<p>The next step was to actually find the streaks. For this, we downloaded the package <code>data.table</code>. This assisted us in finding the longest consecutive strings of consecutive games for each statistic. Using points as an example, if a player had a game with a positive <code>deviationppg</code>, the <code>positive_dev_ppg</code> will be 1. This column is tracked by the <code>Consec_ppg</code> column, which increases by 1 each time a player has a positive deviation in a consecutive game. We accounted for each player, grouping by player within this function to ensure that the streaks don’t overlap players by mistake. We also took this opportunity to find the number of games played by a player in the season. This allows us to plot using game number instead of game date for more consistency.</p>
<table>
<colgroup>
<col width="6%" />
<col width="5%" />
<col width="4%" />
<col width="2%" />
<col width="6%" />
<col width="8%" />
<col width="5%" />
<col width="4%" />
<col width="2%" />
<col width="6%" />
<col width="8%" />
<col width="5%" />
<col width="2%" />
<col width="2%" />
<col width="6%" />
<col width="8%" />
<col width="5%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">player</th>
<th align="left">date</th>
<th align="right">ppg</th>
<th align="right">pts</th>
<th align="right">deviationppg</th>
<th align="right">positive_dev_ppg</th>
<th align="right">Consec_ppg</th>
<th align="right">apg</th>
<th align="right">ast</th>
<th align="right">deviationapg</th>
<th align="right">positive_dev_apg</th>
<th align="right">Consec_apg</th>
<th align="right">rpg</th>
<th align="right">trb</th>
<th align="right">deviationrpg</th>
<th align="right">positive_dev_rpg</th>
<th align="right">Consec_rpg</th>
<th align="right">game_number</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Aaron Gordon</td>
<td align="left">2021-10-20</td>
<td align="right">15.01333</td>
<td align="right">12</td>
<td align="right">-3.0133333</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2.506667</td>
<td align="right">4</td>
<td align="right">1.4933333</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">5.84</td>
<td align="right">8</td>
<td align="right">2.16</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">Aaron Gordon</td>
<td align="left">2021-10-22</td>
<td align="right">15.01333</td>
<td align="right">8</td>
<td align="right">-7.0133333</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2.506667</td>
<td align="right">1</td>
<td align="right">-1.5066667</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">5.84</td>
<td align="right">5</td>
<td align="right">-0.84</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="left">Aaron Gordon</td>
<td align="left">2021-10-25</td>
<td align="right">15.01333</td>
<td align="right">12</td>
<td align="right">-3.0133333</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2.506667</td>
<td align="right">1</td>
<td align="right">-1.5066667</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">5.84</td>
<td align="right">9</td>
<td align="right">3.16</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="left">Aaron Gordon</td>
<td align="left">2021-10-26</td>
<td align="right">15.01333</td>
<td align="right">20</td>
<td align="right">4.9866667</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">2.506667</td>
<td align="right">1</td>
<td align="right">-1.5066667</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">5.84</td>
<td align="right">7</td>
<td align="right">1.16</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="left">Aaron Gordon</td>
<td align="left">2021-10-29</td>
<td align="right">15.01333</td>
<td align="right">13</td>
<td align="right">-2.0133333</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2.506667</td>
<td align="right">2</td>
<td align="right">-0.5066667</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">5.84</td>
<td align="right">5</td>
<td align="right">-0.84</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">5</td>
</tr>
<tr class="even">
<td align="left">Aaron Gordon</td>
<td align="left">2021-10-30</td>
<td align="right">15.01333</td>
<td align="right">12</td>
<td align="right">-3.0133333</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2.506667</td>
<td align="right">2</td>
<td align="right">-0.5066667</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">5.84</td>
<td align="right">4</td>
<td align="right">-1.84</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">6</td>
</tr>
<tr class="odd">
<td align="left">Aaron Gordon</td>
<td align="left">2021-11-01</td>
<td align="right">15.01333</td>
<td align="right">15</td>
<td align="right">-0.0133333</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2.506667</td>
<td align="right">1</td>
<td align="right">-1.5066667</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">5.84</td>
<td align="right">10</td>
<td align="right">4.16</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td align="left">Aaron Gordon</td>
<td align="left">2021-11-03</td>
<td align="right">15.01333</td>
<td align="right">9</td>
<td align="right">-6.0133333</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2.506667</td>
<td align="right">1</td>
<td align="right">-1.5066667</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">5.84</td>
<td align="right">1</td>
<td align="right">-4.84</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">8</td>
</tr>
<tr class="odd">
<td align="left">Aaron Gordon</td>
<td align="left">2021-11-06</td>
<td align="right">15.01333</td>
<td align="right">9</td>
<td align="right">-6.0133333</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2.506667</td>
<td align="right">2</td>
<td align="right">-0.5066667</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">5.84</td>
<td align="right">3</td>
<td align="right">-2.84</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="left">Aaron Gordon</td>
<td align="left">2021-11-08</td>
<td align="right">15.01333</td>
<td align="right">10</td>
<td align="right">-5.0133333</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">2.506667</td>
<td align="right">3</td>
<td align="right">0.4933333</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">5.84</td>
<td align="right">7</td>
<td align="right">1.16</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">10</td>
</tr>
</tbody>
</table>
<p>The above table shows the first 10 rows in the <code>streaks2022</code> dataset, showing the way the streaks were counted. Using this table, we could now see the players with the longest streaks.</p>
<table>
<thead>
<tr class="header">
<th align="left">player</th>
<th align="right">max_streak</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Bruce Brown</td>
<td align="right">18</td>
</tr>
<tr class="even">
<td align="left">Jordan Poole</td>
<td align="right">18</td>
</tr>
<tr class="odd">
<td align="left">Drew Eubanks</td>
<td align="right">16</td>
</tr>
<tr class="even">
<td align="left">Aleksej Pokusevski</td>
<td align="right">13</td>
</tr>
<tr class="odd">
<td align="left">Coby White</td>
<td align="right">13</td>
</tr>
<tr class="even">
<td align="left">Trendon Watford</td>
<td align="right">13</td>
</tr>
<tr class="odd">
<td align="left">Cam Thomas</td>
<td align="right">12</td>
</tr>
<tr class="even">
<td align="left">DeMar DeRozan</td>
<td align="right">12</td>
</tr>
<tr class="odd">
<td align="left">Ben McLemore</td>
<td align="right">11</td>
</tr>
<tr class="even">
<td align="left">De’Anthony Melton</td>
<td align="right">11</td>
</tr>
</tbody>
</table>
<p>As previously theorized, we were able to find that the players with the longest streaks were those who were role players. Only one player (DeMar DeRozan) in the top 10 longest streaks scored over 20 points per game. This would agree with the idea that a longer streak would most likely be accomplished by a player with a lower season average, as a player could be given an opportunity, or go on a ‘hot streak’ to perform above their usual output.</p>
<table>
<thead>
<tr class="header">
<th align="left">player</th>
<th align="right">max_streak</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">DeMar DeRozan</td>
<td align="right">12</td>
</tr>
<tr class="even">
<td align="left">Jaylen Brown</td>
<td align="right">10</td>
</tr>
<tr class="odd">
<td align="left">De’Aaron Fox</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="left">Bradley Beal</td>
<td align="right">8</td>
</tr>
<tr class="odd">
<td align="left">Darius Garland</td>
<td align="right">8</td>
</tr>
<tr class="even">
<td align="left">Devin Booker</td>
<td align="right">8</td>
</tr>
<tr class="odd">
<td align="left">Joel Embiid</td>
<td align="right">8</td>
</tr>
<tr class="even">
<td align="left">Dejounte Murray</td>
<td align="right">7</td>
</tr>
<tr class="odd">
<td align="left">Ja Morant</td>
<td align="right">7</td>
</tr>
<tr class="even">
<td align="left">Julius Randle</td>
<td align="right">7</td>
</tr>
</tbody>
</table>
<p>Even among the best players, scoring over 20 points per game, the majority of players in the top 10 were those scoring in the low 20s. This again fortifies the theory that players who score prolifically in a season are usually less likely to go on streaks, as they are much more consistent and deviate much less significantly or less frequently.</p>
</div>
<div id="further-analysis-of-streaks" class="section level1">
<h1>Further analysis of streaks:</h1>
<p>Of note, for this further analysis, we will only be considering those players who average greater than 25 minutes a game to get the sample size into a managable state. We further break down these games into only those where the target player played greater than 15 minutes. This is to account for players that might have gotten hurt early in a game, or benched for being in foul trouble, early ejections, unfavorable matchups etc. By allowing them to play at least 15 minutes, we are giving the player the best opportunity to match their season average. This also has the added benefit of mitigating players who normally do not have a significant role on their team, but feature more prominently in the offense because of injuries/trades, as these players would have a relatively low season average due to not playing much, and then consistently beating this mark once they have an opportunity to do so. This data is also from 2019-2022, so it is possible for a player to continue their streaks into a new season. Additionally, we will not just be examining a player’s max streak, but rather the players with the highest median streak length. This is a more informative metric, as any one player can have a big run once in a season, but it is much more indicative of a player’s general streakiness if he consistently performs above his averages. We also want to try to account for the fact that some players will score above average only because they get more opportunities to score. We calculate the average usage percentage for a player in a given year, and only include the games where the usage rate falls into this range. This should give us a better sense of the TRUE streakiness of a player in the NBA. Also to note, the data cleaning and statistics are created in a similar but different way from above.</p>
<p>In these graphs we analyze the relationship between streaks defined by just points scored, and a combination of points, rebounds, and assists. The reasoning behind this is that points scored are not the only statistic of value, and many NBA players occupy different roles within an offense that may lead them to play a style of basketball that leads to more rebounds and assists. We theorized that by combining points rebounds and assists, we would represent big men and players whose value does not come from any one area more equitably in the data. Additionally, we are defining a streak as having started once a player performs above their average in 1 game. If the previous game resulted in a below average performance, they will have a “0” game pts streak. As we will see below, most of the time the players score below their average. However, for the sake of limiting the scope of our analysis, we are not interested in determining negative streaks, and will instead focus on instances of positive streaks.
<img src="/analysis_files/figure-html/further%20EDA-1.png" width="672" /></p>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   0.000   0.000   1.045   1.000  20.000</code></pre>
<p><img src="/analysis_files/figure-html/further%20EDA-2.png" width="672" /></p>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   0.000   0.000   1.118   1.000  21.000</code></pre>
<p>Interestingly, there does not seem to much of a defined difference in the two distributions, and that a players streakiness can be reasonably well measured by one or the other. Next, lets take a closer look at some individual players and see how they are performing in 2022 by both points and P+R+A
<img src="/analysis_files/figure-html/player%20analysis-1.png" width="672" /><img src="/analysis_files/figure-html/player%20analysis-2.png" width="672" /></p>
<p>Below, we compare two of the NBA’s streakiest players, OG Anunoby of the Toronto Raptors and Josh Hart of the Portland Trailblazers to Stephen Curry, one of the leagues best overall players. In the games that Steph managed to play in 2022 due to injury, he actually went on a 2 game above average streak. But he could not consistently score above his average consistently, wheras OG and Josh Hart consistently went on longer runs.</p>
<p><img src="/analysis_files/figure-html/specific%20player%20analysis-1.png" width="672" /><img src="/analysis_files/figure-html/specific%20player%20analysis-2.png" width="672" /><img src="/analysis_files/figure-html/specific%20player%20analysis-3.png" width="672" /><img src="/analysis_files/figure-html/specific%20player%20analysis-4.png" width="672" /><img src="/analysis_files/figure-html/specific%20player%20analysis-5.png" width="672" /><img src="/analysis_files/figure-html/specific%20player%20analysis-6.png" width="672" /></p>
</div>
<div id="modeling-and-inference" class="section level1">
<h1>Modeling and inference:</h1>
<p>To include a more formal statistical inference, we created two separate models to try to understand the probability that a team/player will perform above average, and which factors weigh most heavily in this decision. The first model is a logistic regression model trained on player data that gives us the probability that a player will perform above their average. We identified key variables most relevant to our question as our explanatory variables, and include one interaction term. The formula is as follows: glm(formula=factor(pts_direction)~ts_pct+usg_pct+usg_pct:ts_pct,family=binomial()). Ultimately, we are less interested in the predictive capability of this model, and instead more interested by how it allows us to see changes in probability as the explanatory variables change. Due to the massive number of variables present in the NBA data, we did not perform any model selection for the NBA model, but we handpicked variables that we believed to be the most relevant. Below, we can see that even after accounting for different usage percentages, one of the biggest individual factor in determining whether or not a player will score above their average in many cases is actually their usage percentage. This is somewhat intuitive, as the opportunity to score is a key step to scoring above average. This is further validated by some of the top performers, such as Josh Hart and OG Anunoby, who consistently scored above their average once they were given more offensive responsibilities.As a result of this finding, we will look into more ways to quantify a player’s streakiness.</p>
<pre><code>## 
## Call:
## glm(formula = factor(pts_direction) ~ ts_pct + usg_pct + usg_pct:ts_pct, 
##     family = binomial(), data = .)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -4.5857  -0.6435  -0.1898   0.6760   2.4712  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     -4.3299     0.2759 -15.696  &lt; 2e-16 ***
## ts_pct           0.8924     0.4170   2.140   0.0324 *  
## usg_pct         -8.2446     1.5895  -5.187 2.14e-07 ***
## ts_pct:usg_pct  49.4248     2.6966  18.329  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 14730.4  on 10667  degrees of freedom
## Residual deviance:  9081.7  on 10664  degrees of freedom
## AIC: 9089.7
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<pre><code>## [1] 132993.7</code></pre>
<p><img src="/analysis_files/figure-html/nba%20model%201-1.png" width="672" /></p>
<p><br></p>
<p>For this cross-sport analysis, we filtered through NBA players who played at least 2000 minutes in the 2021-22 NBA season. Our stat of choice for our first linear regression was Average Plus-Minus, which is a stat that measures how much a player’s team outscores their opponent per game when they’re on the floor. Of our sample of players, the mean Plus-Minus was around +2. Like our OPS plot, we plot a player’s Average Plus-Minus against their percentage of games above +2:</p>
<p>##Further NBA analysis
For the sake of consistency, we will apply the same analysis to the MLB data to the NBA despite some of the inherent differences in the two leagues. First, we load the data in and create our streaks in the same way as the MLB.
<br></p>
<pre><code>## 
## Call:
## lm(formula = per ~ epm, data = sim)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.089702 -0.021918 -0.000186  0.029953  0.090681 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 0.460129   0.004059  113.37   &lt;2e-16 ***
## epm         0.029916   0.001072   27.91   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.03629 on 94 degrees of freedom
## Multiple R-squared:  0.8923, Adjusted R-squared:  0.8912 
## F-statistic: 779.1 on 1 and 94 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><img src="/analysis_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p><br></p>
<p>Also like our MLB analysis further below, we labeled players as either “streaky” or “consistent” based on their standardized residuals of the previous model. However, unlike our MLB analysis, we could not find many stats that could produce statistically significant results for predicting a player’s streakiness. The best one we could find was Usage Pct, which is a stat that measures how often a player handles the ball when his team is on offense.</p>
<p><br></p>
<p>Here are the plots for our logistic regression:
<br></p>
<pre><code>## 
## Call:
## glm(formula = streaky ~ up, family = binomial, data = log_sim)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -1.39902  -1.16854   0.01669   1.12942   1.43336  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)  1.13779    0.85389   1.332    0.183
## up          -0.04914    0.03582  -1.372    0.170
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 133.08  on 95  degrees of freedom
## Residual deviance: 131.15  on 94  degrees of freedom
## AIC: 135.15
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p><img src="/analysis_files/figure-html/unnamed-chunk-3-1.png" width="672" />
And linear regression:</p>
<p><br></p>
<pre><code>## 
## Call:
## lm(formula = s_res ~ up, data = log_sim)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.62152 -0.60318  0.00401  0.85677  2.58556 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -0.31478    0.41993  -0.750    0.455
## up           0.01358    0.01758   0.773    0.442
## 
## Residual standard error: 1.008 on 94 degrees of freedom
## Multiple R-squared:  0.006312,   Adjusted R-squared:  -0.004259 
## F-statistic: 0.5971 on 1 and 94 DF,  p-value: 0.4416</code></pre>
<p><img src="/analysis_files/figure-html/unnamed-chunk-4-1.png" width="672" />
<br></p>
<p>Intuitively, we can reason that players with the ball in their hands more often have more opportunities to affect the game in some way, meaning they are more likely to balance out their positives and negatives on the court, creating more consistent play on a game to game basis. However, it is still not a statistically significant predictor of streakiness. This analysis is interesting, considering how usage rate is so impactful in some of our other models.</p>
<p><br></p>
<p>There are some limitations to this analysis. For one, baseball and basketball are different in a sense that there are more opportunities for players to contribute in a basketball game than a baseball game. Top NBA players take around 15-20 field goals and 5-10 free throws a game, whereas the top MLB players get around 4-5 plate appearances a game. Therefore, this type of analysis is better suited for baseball, because a player’s production in a single game can vary drastically from their season average more so than in basketball. In addition, it generalizes streakiness as a concept to a great degree, and does not cover game-to-game streaks.</p>
<p><br></p>
<p>We also performed a different analysis of streaks in MLB to cover for these shortcomings, and used that analysis to tie in similarities to our NBA analysis.</p>
<p><br></p>
<div id="mlb-broad-analysis" class="section level2">
<h2>MLB Broad Analysis</h2>
<p>To generalize the concept of “streakiness” in MLB, we wanted to find out if there was one single stat that could most strongly predict whether a batter is streaky or not.</p>
<p><br></p>
<pre><code>## Warning: package &#39;ggrepel&#39; was built under R version 4.2.2</code></pre>
<pre><code>## Rows: 61316 Columns: 24
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr   (5): game_id, team_abbrev, player_id, player, details
## dbl  (18): ab, r, h, rbi, bb, so, pa, batting_order, doubles, triples, home_...
## date  (1): game_date
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p><br></p>
<p>The primary stat that we used to determine a player’s value in this analysis is OPS since it is generally considered among statisticians and managers as one of the better metrics of a player’s worth. We calculated among all qualifying players (at least 502 plate appearances) the percentage of their games where they recorded an OPS above the league average of 0.726 and plotted it against their total OPS for the season. Intuitively, we would expect players with higher overall OPS to have a higher percentage of games where they performed above league average, and that’s what we see here:</p>
<p><br></p>
<pre><code>## 
## Call:
## lm(formula = per ~ ops, data = sim_21)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.070344 -0.019602  0.001755  0.019199  0.072926 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.03762    0.02348   1.603    0.111    
## ops          0.53782    0.02934  18.331   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.02787 on 133 degrees of freedom
## Multiple R-squared:  0.7164, Adjusted R-squared:  0.7143 
## F-statistic:   336 on 1 and 133 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><img src="/analysis_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p><br></p>
<p>Fitting a linear regression to this data, we find a statistically significant correlation. For our step, we standardized the residuals and determined that players with high magnitude positive residuals were the most “consistent,” and ones with high magnitude negative residuals were the most “streaky.” Why is this? We would expect more streaky players to have a small number of games with big production and a large number of below average games.</p>
<p><br></p>
<p>To visualize this decision, here’s a game log of Jose Altuve, who is the most consistent player by our residual measure. The graph represents games where performed above or below his OWN average OPS, and the red line represents the MLB average:</p>
<p><br></p>
<p><img src="/analysis_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p><br></p>
<p>And here’s a game of log of Nathaniel Lowe, who is the most streaky player:</p>
<p><br></p>
<p><img src="/analysis_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p><br></p>
<p>Now we turned to analyze if there was a single stat that could most accurately predict whether a player was streaky or not. At first, we thought that walks would be the best stat, because of the idea that some players are “free swingers;” players that swing at a ton of pitches, don’t draw many walks, but are still on the roster because of their ability to get hot at certain times. However, walks ended up not being a great predictor. We also tried home runs, but that wasn’t a great predictor either.</p>
<p><br></p>
<p>Out of all stats we tried, strikeouts was the best predictor as seen by this linear regression:</p>
<p><br></p>
<pre><code>## 
## Call:
## lm(formula = s_res_21 ~ so, data = log_sim_21)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.40988 -0.62661  0.04148  0.66019  2.31564 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.195161   0.326803   3.657 0.000366 ***
## so          -0.009686   0.002564  -3.778 0.000237 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9565 on 133 degrees of freedom
## Multiple R-squared:  0.09694,    Adjusted R-squared:  0.09015 
## F-statistic: 14.28 on 1 and 133 DF,  p-value: 0.0002372</code></pre>
<p><img src="/analysis_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p><br></p>
<p>As well as this logistic regression, where we labeled players as streaky or consistent by the SIGN of their residuals:</p>
<p><br></p>
<pre><code>## 
## Call:
## glm(formula = streaky ~ so, family = binomial, data = log_sim_21)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.8009  -1.0094  -0.6432   1.0926   2.1344  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept) -3.193448   0.818225  -3.903  9.5e-05 ***
## so           0.024972   0.006438   3.879 0.000105 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 186.79  on 134  degrees of freedom
## Residual deviance: 168.82  on 133  degrees of freedom
## AIC: 172.82
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p><img src="/analysis_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p><br></p>
<p>So we conclude that “free swingers” are not necessarily the streaky players, but rather the “swing for the fences” type of players, meaning players that swing as hard as they can as much as they can in order to hit more home runs, but at the cost of striking out more. It is also interesting to note how strikeouts were correlated to streakiness in a statistically significant way but not home runs, meaning the act of “swinging for the fences” relates to streakiness whether or not the players are actually successful in hitting more home runs.</p>
</div>
<div id="further-mlb-analysis" class="section level2">
<h2>Further MLB analysis</h2>
<p>For the sake of consistency, we also attempted to apply the same analysis to the MLB data to the NBA.</p>
<p>As we see below, the MLB has a very similar distribution of hits to points and points +rebounds+assists. Many of its top players interestingly seem to go on longer streaks more often than their NBA counterparts.</p>
<p><img src="/analysis_files/figure-html/Final%20player%20EDA-1.png" width="672" /></p>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   0.000   0.000   0.834   1.000  19.000</code></pre>
<p><img src="/analysis_files/figure-html/Final%20player%20EDA-2.png" width="672" /></p>
<p>Below, we look at the top performers in the MLB. As we saw above, Austin Hays and Yoan Moncada are the top performers in the MLB, with pitcher Yu Darvish giving us the lowest streakiness, most likely due to his low number of plate appearances.</p>
<pre class="r"><code>scoring&lt;-all_data_mlb %&gt;% filter(player == &#39;Austin Hays&#39;) %&gt;%select(change_net,game_date,h_streak)
ggplot(scoring, aes(x=as.Date(as.factor(game_date)), y=change_net, group=1)) +
geom_ribbon(aes(ymin=pmin(change_net,0), ymax=0), fill=&quot;red&quot;, col=&quot;red&quot;, alpha=0.5) +
geom_ribbon(aes(ymin=0, ymax=pmax(change_net,0)), fill=&quot;green&quot;, col=&quot;green&quot;, alpha=0.5) +
geom_point()+
geom_line(aes(y=0)) + ggtitle(&#39;Austin Hays Hits Deviated from Average&#39;) +
ylab(&#39;Hits Deviated from Average&#39;) +
xlab(&#39;Date&#39;)</code></pre>
<p><img src="/analysis_files/figure-html/contuining%20MLB%20player%20analysis%202-1.png" width="672" /></p>
<pre class="r"><code>ggplot(scoring,aes(h_streak))+stat_ecdf(geom = &quot;step&quot;)+ labs(title=&#39;Austin Hays Hits Streak CDF&#39;, x=&quot;Hits Streak&quot;, y=&quot;CDF&quot;) </code></pre>
<p><img src="/analysis_files/figure-html/contuining%20MLB%20player%20analysis%202-2.png" width="672" /></p>
<pre class="r"><code>scoring&lt;-all_data_mlb %&gt;% filter(player == &#39;Yoan Moncada&#39;) %&gt;%select(change_net,game_date,h_streak)
ggplot(scoring, aes(x=as.Date(as.factor(game_date)), y=change_net, group=1)) +
geom_ribbon(aes(ymin=pmin(change_net,0), ymax=0), fill=&quot;red&quot;, col=&quot;red&quot;, alpha=0.5) +
geom_ribbon(aes(ymin=0, ymax=pmax(change_net,0)), fill=&quot;green&quot;, col=&quot;green&quot;, alpha=0.5) +
geom_point()+
geom_line(aes(y=0)) + ggtitle(&#39;Yoan Moncada Hits Deviated from Average&#39;) +
ylab(&#39;Hitss Deviated from Average&#39;) +
xlab(&#39;Date&#39;)</code></pre>
<p><img src="/analysis_files/figure-html/contuining%20MLB%20player%20analysis%202-3.png" width="672" /></p>
<pre class="r"><code>ggplot(scoring,aes(h_streak))+stat_ecdf(geom = &quot;step&quot;) + labs(title=&#39;Yoan Moncada Hits Streak CDF&#39;, x=&quot;Hits Streak&quot;, y=&quot;CDF&quot;)  </code></pre>
<p><img src="/analysis_files/figure-html/contuining%20MLB%20player%20analysis%202-4.png" width="672" /></p>
<pre class="r"><code>scoring&lt;-all_data_mlb %&gt;% filter(player == &#39;Yu Darvish&#39;) %&gt;%select(change_net,game_date,h_streak)
ggplot(scoring, aes(x=as.Date(as.factor(game_date)), y=change_net, group=1)) +
geom_ribbon(aes(ymin=pmin(change_net,0), ymax=0), fill=&quot;red&quot;, col=&quot;red&quot;, alpha=0.5) +
geom_ribbon(aes(ymin=0, ymax=pmax(change_net,0)), fill=&quot;green&quot;, col=&quot;green&quot;, alpha=0.5) +
geom_point()+
geom_line(aes(y=0)) + ggtitle(&#39;Yu Darvish Hits Deviated from Average&#39;) +ylab(&#39;Hits Deviated from Average&#39;) +
xlab(&#39;Date&#39;)</code></pre>
<p><img src="/analysis_files/figure-html/contuining%20MLB%20player%20analysis%202-5.png" width="672" /></p>
</div>
<div id="similarities-between-the-nba-and-mlb" class="section level2">
<h2>Similarities between the NBA and MLB</h2>
<p>Finally, let’s look at the comparisons in aggregate data in the NBA and MLB by points, PRA, and hits more in depth. There is a very similar trend among each league, and the distributions match very closely. This may point to the presence of a more universal trait regarding athletes ability to perform above average across long periods of time, not limited to any one league.</p>
<p><img src="/analysis_files/figure-html/comparison%201-1.png" width="672" /><img src="/analysis_files/figure-html/comparison%201-2.png" width="672" /></p>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   0.000   0.000   1.045   1.000  20.000</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.000   0.000   0.000   0.834   1.000  19.000</code></pre>
<p>Next, lets look at the top performers in the MLB and the NBA. Austin Hays had the highest median streak length in the MLB, and Josh Hart had the second highest in the same category in the NBA. Below, we see the top 5 performers in each league, along with the distribution of streaks and the top players spike plot. As we can see, the top players in the MLB go on longer streaks more frequently than in the NBA.
<img src="/analysis_files/figure-html/comparison%202-1.png" width="672" /><img src="/analysis_files/figure-html/comparison%202-2.png" width="672" /><img src="/analysis_files/figure-html/comparison%202-3.png" width="672" /><img src="/analysis_files/figure-html/comparison%202-4.png" width="672" />
Again, the results are fairly similar and somewhat surprising. It is interesting to note that some of the top player match each others streakiness quite well. Austin Hays however, completes more sustained runs of games with hits, whereas Josh Hart seems to have gone on only a couple longer runs.
For the final comparison, we will use the models we have trained to see if the predictive capabilities of the models are similar.
Unfortunately, we can’t use quite the same visualizations for the model, since the range of the number of hits is greatly constrained compared to the offensive rating of a player. We see that the NBA model is more accurate in its predictive capabilities for the top players. This is most likely because just the batting average,walks,and plate appearances are not enough to capture a players hit capabilities. Another surprising result is in the summary statistics of each model. All model predictors have 3 star significant codes except for true shooting percentage. This seems counter intuitive, as how well a player shoots on a given night should factor very heavily into how much above average they perform. However, in our analysis we thought that a players given offensive production is largely determined by how often they have a chance to shoot AND their shooting percentage, so we included an interaction term between true shooting percentage and usage percentage to factor in this intuition. Ultimately, it still appears that the opportunity to score both in baseball and basketball seems to be the most relevant statistic in this analysis.</p>
<pre><code>## 
## Call:
## glm(formula = factor(pts_direction) ~ ts_pct + usg_pct + usg_pct:ts_pct, 
##     family = binomial(), data = .)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -3.4184  -0.6447  -0.2091   0.6937   2.2918  
## 
## Coefficients:
##                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)     -3.8054     0.4533  -8.395  &lt; 2e-16 ***
## ts_pct           0.2602     0.6722   0.387    0.699    
## usg_pct        -11.2751     2.6256  -4.294 1.75e-05 ***
## ts_pct:usg_pct  52.3961     4.4009  11.906  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 4990.4  on 3619  degrees of freedom
## Residual deviance: 3131.9  on 3616  degrees of freedom
## AIC: 3139.9
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<pre><code>## [1] 74.03197</code></pre>
<pre><code>## 
## Call:
## glm(formula = factor(h_direction) ~ pa + ba + bb + so, family = binomial(), 
##     data = .)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.7417  -0.9917  -0.2283   0.9644   4.9077  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)   0.862020   0.029734   28.99   &lt;2e-16 ***
## pa            0.790980   0.009259   85.42   &lt;2e-16 ***
## ba          -13.695735   0.185291  -73.92   &lt;2e-16 ***
## bb           -0.666143   0.018179  -36.64   &lt;2e-16 ***
## so           -0.722153   0.012549  -57.55   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 78703  on 56777  degrees of freedom
## Residual deviance: 67087  on 56773  degrees of freedom
##   (4536 observations deleted due to missingness)
## AIC: 67097
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre><code>## [1] 1524531</code></pre>
<p>To recap, below are the two logistic regression models on strikeouts and usage rate, and the two linear plots on OPS and plsu minus compared to above average performances. As we see below, OPS and plus minus are similarly distributed, suggesting that what a players advanced stats are in both leagues affect streakiness. Additionally, unlike the NBA, strikeouts provide a meaningful statistic to predict streakiness, as explained by the “swing for the fence mentality” that may not be present in the NBA.
<img src="/segmented_plots/log_strikeouts.png" alt="log_strikeouts" />
<img src="/segmented_plots/usage_rate.png" alt="log_usage_rate" />
<img src="/segmented_plots/OPS.png" alt="OPS" />
<img src="/segmented_plots/plus_minus.png" alt="plus_minus" /></p>
</div>
<div id="flawslimitations" class="section level2">
<h2>Flaws/Limitations:</h2>
<p>One of the main flaws in this analysis are the innate differences of basketball and baseball in both offensive and defensive aspects of the game. Baseball, especially when on offense, is a more individualistic game, whereas basketball relies heavily on the entire team. When a player is batting, their only objective is to hit the ball, while a basketball player may have to pass, changing the potential outcome, especially for those players with high usage rate. These innate differences cause difficulty when trying to make a 1:1 assessment between the two leagues.</p>
</div>
</div>
<div id="modeling-flawslimitations" class="section level1">
<h1>Modeling flaws/limitations:</h1>
<p>Initially, we had created an xgboost model to predict whether a player would score above their average. However, this type of model does not offer much interpretability so we went with a logistic regression model. Additionally, we are assuming that streakiness can be explained purely by the stats we have been given. In reality, these are humans with their own personal motivations, weaknesses, sick days, etc. For example, we know certain great players such as Kobe Bryant and Michael Jordan have performed some of their greatest statistical feats due to grudges, sense of pride, and feeling insulted by other players who doubted their ability. Other players, such as Isaiah Thomas of the celtics, dedicated his most statistically positive season to his sister who had tragically passed away. It is difficult to capture these in person motivations, and they have not been accounted for. Another initial inherent limitation is that we are not taking into account some factors that could have an impact on player performance within their team. For example, one of the highest performers in the NBA in our analysis is Josh Hart. What we fail to take into account is that Josh Hart was traded from the New Orleans Pelicans to the Portland Trailblazers in the middle of the 2022 season. His role changed from that of a bench player, to a main scorer and contributor for his team. OG Anunoby, another high performer, saw his role on the Raptors increase drastically as the team began looking to him for more offensive production as his role changed from a developing rookie to a core part of a mature NBA offense. Because we define a streak as performing above their average over their whole career, players such as this may not have their innate “streakiness” accurately measured. This is further outlined by how much usage percentage factors into a players probability of scoring above average. Simply getting more opportunities to score will obviously affect a players offensive output. While we try to mitigate injuries and limit our analysis only to players to are scoring within their average usage percentage range, there may still be outliars. The true sense of players “streakiness” may not be captured by our statistical methods.</p>
</div>
<div id="pace-modeling" class="section level1">
<h1>Pace Modeling</h1>
<p>Though streaks are generally thought of as consecutive successes, we can also model a player’s streakiness by his variation is pace throughout the season. This approach allows us to broaden our analysis from the game-to-game perspective analyzed above to the overall season. We can then compare this value to the player’s total output to determine to what extent streakiness plays into final season numbers. To do so, we first modeled each player’s cumulative stats throughout the season as a piece-wise linear function using the <code>segmented</code> library, where the slope of each segment represents the pace of the player during that set of games. For example, Salvador Perez’s walks during the 2021 season can be neatly separated into 7 groups of games with different paces.</p>
<div class="figure">
<img src="/segmented_plots/Salvador_Perez_Walks.png" alt="" />
<p class="caption">Salvador_Perez</p>
</div>
<p>This analysis was performed for every qualifying MLB player’s (&gt;=502 plate appearances) cumulative hits, walks, strike outs, and home runs as well as every qualifying NBA player’s (&gt;=58 games and &gt;= 15 minutes per game) cumulative points, assists, and rebounds. To perform the analysis, we used the <code>segmented</code> function to automatically infer the number and locations of segments. To prevent this function’s known limitation of overestimating the number of segments, we made sure to increase the number of iterations and further filter the home runs data to only those players with at least 15 home runs such that the cumulative totals could reasonably be broken down into different paces. The results of the modelling for each individual player can be seen in the shiny application on the Big Picture page.</p>
<p>The next step was to measure the variability of paces for each player and stat and combine them. To do so, we defined the pace streakiness as the standard deviation of the player’s paces for the given stat weighted by the length (in games) that the player performed at each pace. Intuitively, this means that a player is more streaky the more he changes pace and the shorter he holds each pace for. This measure allows us to compare different players along the same stat throughout the entire season. For example, Salvador Perez’s walk streakiness would be 0.137 while AL MVP Shohei Ohtani’s walk streakiness was 0.376.</p>
<p>After calculating the pace streakiness for each player and stat, we explored whether pace streakiness was correlated to final totals in each stat (correclation coefficient) and what percent of the final total variance could be described by the pace streakiness of the player (R^2 value).</p>
<div id="mlb" class="section level2">
<h2>MLB</h2>
<div id="home-runs" class="section level3">
<h3>Home Runs</h3>
<p>The following plot shows the pace streakiness of each player with respect to home runs as compared against his total home runs for the season. Out of the qualifying players, Salvador Perez had the highest streakiness at 0.246 and J.T. Realmuto had the lowest at 0.024. The streakiness and final season values had a weak correlation of 0.382 and a low R^2 value of 0.146. This means that streakiness plays some part in raising the total number of home runs that a player will hit in a season. This makes sense because it takes a lot of power to hit home runs, but it is hard enough to do that a random luck has a little bit of an effect.
<img src="/segmented_plots/HR.png" alt="HR_" /></p>
</div>
<div id="hits" class="section level3">
<h3>Hits</h3>
<p>The following plot shows the pace streakiness of each player with respect to hits as compared against his total hits for the season. Out of the qualifying players, Miguel Cabrera had the highest streakiness at 0.552 and Salvador Perez had the lowest at 0.105. The streakiness and final season values had an insignificant correlation of -0.113 and an insignificant R^2 value of 0.013. This means that streakiness plays almost no part in raising the total number of hits that a player will hit in a season (and may even lower the number of hits a player gets). This makes sense because a player’s ability to get hits is really about his consistency to do so day after day.
<img src="/segmented_plots/Hit.png" alt="HIT" /></p>
</div>
<div id="strike-outs" class="section level3">
<h3>Strike Outs</h3>
<p>The following plot shows the pace streakiness of each player with respect to strike outs as compared against his total strike outs for the season. Out of the qualifying players, Trevor Story had the highest streakiness at 0.48 and Carlos Santana had the lowest at 0.105. The streakiness and final season values had a low correlation of 0.365 and a low R^2 value of 0.134. This means that streakiness plays some part in raising the total number of strike outs that a player will get in a season.
<img src="/segmented_plots/SO.png" alt="SO_" /></p>
</div>
<div id="walks" class="section level3">
<h3>Walks</h3>
<p>The following plot shows the pace streakiness of each player with respect to walks as compared against his total walks for the season. Out of the qualifying players, Aaron Judge had the highest streakiness at 0.395 and Michael Taylor had the lowest at 0.021. The streakiness and final season values had a moderate correlation of 0.518 and a moderate R^2 value of 0.2687. This means that streakiness plays a decent part in raising the total number of walks that a player will get in a season. This makes sense because a player’s ability to draw a walk is dependent on his focus on a given day to not swing at bad pitches (which can be hot or cold depending on his mentality at a given time).
<img src="/segmented_plots/BB.png" alt="BB_" /></p>
</div>
</div>
<div id="nba" class="section level2">
<h2>NBA</h2>
<div id="points" class="section level3">
<h3>Points</h3>
<p>The following plot shows the pace streakiness of each player with respect to points as compared against his total points for the season. Out of the qualifying players, RJ Barrett had the highest streakiness at 6.375 and<br />
Miles Bridges had the lowest at near zero. The streakiness and final season values had a low correlation of 0.315 and a low R^2 value of 0.099. This means that streakiness plays some part in raising the total number of points that a player will get in a season.
<img src="/segmented_plots/PTS.png" alt="PTS" /></p>
</div>
<div id="assists" class="section level3">
<h3>Assists</h3>
<p>The following plot shows the pace streakiness of each player with respect to assists as compared against his total points for the season. Out of the qualifying players, Davion Mitchell had the highest streakiness at 2.626 and<br />
JaMychal Green had the lowest at 0.131. The streakiness and final season values had a high correlation of 0.668 and a high R^2 value of 0.4467. This means that streakiness plays a large part in raising the total number of assists that a player will get in a season. This makes sense because a player’s assists are heavilly dependent on interactions with fellow teammates, which can be hot or cold seemingly randomly.
<img src="/segmented_plots/AST.png" alt="AST" /></p>
</div>
<div id="rebounds" class="section level3">
<h3>Rebounds</h3>
<p>The following plot shows the pace streakiness of each player with respect to rebounds as compared against his total points for the season. Out of the qualifying players, Andre Drummond had the highest streakiness at 2.78 and<br />
Kyle Anderson had the lowest at 0.138. The streakiness and final season values had a moderate correlation of 0.494 and a moderate R^2 value of 0.244. This means that streakiness plays a decent part in raising the total number of points that a player will get in a season.
<img src="/segmented_plots/RB.png" alt="RB_" /></p>
</div>
</div>
<div id="flawslimitations-1" class="section level2">
<h2>Flaws/Limitations</h2>
<p>The biggest flaw in the segmented model methodology is that there is no perfect way to break up data into linear segments. This is because you can always “increase the fit” by adding more and more line segments. What we attempt to do is find some sort of meaningful balance of accuracy and the number of segments. To do so, we rely on the cost function in the undelying machine learning model in the <code>segmented</code> function to properly penalize having too many line segments. However, the designers of this function do note that it is prone to overestimating the number of segments. Additionally, the slope of each segment is reflects some sort of average pace within the line segment. This means that each “pace” is not really exact and has some variability that is hard to measure.</p>
</div>
</div>
