---
title: Week 8 Blog
author: Haroon, Leo, Ryan, Benni
date: '2022-12-12'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-12-12T17:58:02-05:00'
featuredVideo: ~
featuredImage: ~
---
## Looking back on our analysis and Reflecting on the process:

Our analysis between the two leagues required some ways to mediate the differences between the two leagues. Because the leagues were so different, we needed to find a way to make the threshold of the two leagues a bit more similar. One way we have considered doing this is creating a definition of a streak that is translatable between leagues, despite the statistics being different, like a player scoring above his season average. This allows us to look at players in a more generalized way. One thing we made sure to do was try to add context to why some players performed above their usual means. Some times, streaks are consequences of new opportunity or circumstances that are not reflected in statistics alone. For example, a player like Isaiah Thomas, a former player for the Celtics, dedicated his best season to his sister who passed away in a car crash, and performed his most impressive playoff run on her death's heels. These types of motivations are difficult to assess through statistics alone, and each player's playing situation, personal life, etc. could be further scrutinized to create a narrative and context for their performance. Looking at Josh Hart, one player who stood out in our analysis, his high performance was allowed due to a trade occurred that moved him to a team that specifically sought to expand his role. Our definition of a streak could be improved to perhaps better account for this type of context, although it may be easier to accomplish starting with one sports league so that the differences in game play are not a factor. 

## Deeper Look into the data:

To take a deeper look we will analyze players beyond just points as the main metric. Obviously there are many statistics that a player can impact the game, whether it be with OPS, assists, etc. For the NBA, one way we plan on chiseling the dataset further is only look at players who played 25 minutes a game per season, and then look at individual games to see if the player played at least 15 min. This way, games where players were taken out for injury or fouling out too early, or any other reason that would affect their ability to have a reasonable amount of time for typical offensive production is taken into account. This way they are given a enough time within reason to play most of a normal game. We also expanded from one season to the 2019-2022 seasons (This is the entire extent provided by the source website Advanced Sports Analytics). This also allows a player to continue their streak past one season, giving a more robust profile of their playing production.We will also expand our view beyond their highest max streak, and instead turn our attention to the highest number of streaks, which is more clearly defined as those players with the highest average streak value. This way, streakiness is more of a sign of general inconsistency of increased production, as even those who have maximum streaks are displaying consistency to an above average degree. We will analyze a combination of metrics, to assess players who have more defined roles within their team that facilitate scoring but not necessarily do it themselves

